name: Example Workflow

# Defines when the workflow should run. 
# This example triggers the workflow on every push to the repository.
on: [push]

# Jobs are a set of steps that execute on the same runner.
jobs:
  build:
    # Specifies the type of runner that the job will run on.
    runs-on: ubuntu-latest
    
    # A sequence of commands or actions that are executed as part of the job.
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
